repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.13
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
        files: ^(chromodet|projects)/
      - id: ruff-format
        files: ^(chromodet|projects)/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: check-merge-conflict
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        files: ^(chromodet|projects)/
  - repo: https://github.com/open-mmlab/pre-commit-hooks
    rev: v0.2.0
    hooks:
      - id: check-algo-readme
      - id: check-copyright
        args: ["chromodet"]
