auto_scale_lr = dict(base_batch_size=16, enable=False)
backend = 'pillow'
backend_args = None
custom_imports = dict(
    allow_failed_imports=False,
    imports=[
        'projects.DiffusionDet.diffusiondet',
    ])
data_root = '/media/ross/8TB/project/lsh/chromosome/dataset/seflmake/chromosome202250604_NoResizeNoAug/'
dataset_type = 'CocoDataset'
default_hooks = dict(
    checkpoint=dict(
        _scope_='mmdet',
        by_epoch=True,
        interval=1,
        max_keep_ckpts=20,
        rule='greater',
        save_best='coco/bbox_mAP',
        type='CheckpointHook'),
    early_stopping=dict(
        min_delta=0.002,
        monitor='coco/bbox_mAP',
        patience=15,
        type='EarlyStoppingHook'),
    logger=dict(_scope_='mmdet', interval=50, type='LoggerHook'),
    param_scheduler=dict(_scope_='mmdet', type='ParamSchedulerHook'),
    sampler_seed=dict(_scope_='mmdet', type='DistSamplerSeedHook'),
    timer=dict(_scope_='mmdet', type='IterTimerHook'),
    visualization=dict(
        _scope_='mmdet',
        draw=True,
        show=False,
        test_out_dir='visualization_results',
        type='DetVisualizationHook',
        wait_time=2))
default_scope = 'mmdet'
env_cfg = dict(
    cudnn_benchmark=False,
    dist_cfg=dict(backend='nccl'),
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0))
launcher = 'none'
log_level = 'INFO'
log_processor = dict(
    _scope_='mmdet', by_epoch=True, type='LogProcessor', window_size=50)
model = dict(
    backbone=dict(
        depth=50,
        frozen_stages=1,
        init_cfg=dict(checkpoint='torchvision://resnet50', type='Pretrained'),
        norm_cfg=dict(requires_grad=True, type='BN'),
        norm_eval=True,
        num_stages=4,
        out_indices=(
            0,
            1,
            2,
            3,
        ),
        style='pytorch',
        type='ResNet'),
    bbox_head=dict(
        adem_head=dict(
            in_channels=256,
            loss_weight=0.3,
            max_sigma=2.0,
            min_sigma=0.1,
            num_scales=3,
            type='ADEMHead'),
        adem_loss_weight=0.3,
        base_steps=3,
        complexity_thresh=0.5,
        criterion=dict(
            assigner=dict(
                candidate_topk=5,
                center_radius=2.5,
                match_costs=[
                    dict(
                        alpha=0.25,
                        eps=1e-08,
                        gamma=2.0,
                        type='FocalLossCost',
                        weight=2.0),
                    dict(box_format='xyxy', type='BBoxL1Cost', weight=5.0),
                    dict(iou_mode='giou', type='IoUCost', weight=2.0),
                ],
                type='DiffusionDetMatcher'),
            loss_bbox=dict(loss_weight=5.0, reduction='sum', type='L1Loss'),
            loss_cls=dict(
                alpha=0.25,
                gamma=2.0,
                loss_weight=2.0,
                reduction='sum',
                type='FocalLoss',
                use_sigmoid=True),
            loss_giou=dict(loss_weight=2.0, reduction='sum', type='GIoULoss'),
            num_classes=24,
            type='EnhancedDiffusionDetCriterion'),
        ddim_eta=0.2,
        ddim_sampling_eta=1.0,
        deep_supervision=True,
        distill_weight=0.3,
        dynamic_steps=20,
        enable_distill=False,
        feat_channels=256,
        lcm_guidance_scale=1.0,
        num_classes=24,
        num_heads=6,
        num_proposals=500,
        prior_prob=0.01,
        roi_extractor=dict(
            featmap_strides=[
                4,
                8,
                16,
                32,
            ],
            out_channels=256,
            roi_layer=dict(output_size=7, sampling_ratio=2, type='RoIAlign'),
            type='SingleRoIExtractor'),
        sampling_timesteps=1,
        single_head=dict(
            act_cfg=dict(inplace=True, type='ReLU'),
            dim_feedforward=2048,
            dropout=0.0,
            dynamic_conv=dict(dynamic_dim=64, dynamic_num=2),
            num_cls_convs=1,
            num_heads=8,
            num_reg_convs=3,
            type='EnhancedSingleDiffusionDetHead',
            use_lcm=True),
        small_object_distill=False,
        small_object_distiller=dict(
            adaptive_thresh=True,
            base_temp=1.5,
            max_area_thresh=0.03,
            min_area_thresh=0.008,
            small_temp=0.8,
            type='SmallObjectAwareDistillation',
            use_mixed_precision=True),
        snr_scale=2.0,
        teacher_config=dict(
            ddim_sampling_eta=0.0,
            num_proposals=500,
            sampling_timesteps=25,
            timesteps=1000),
        type='EnhancedDiffusionDetHead',
        use_adem=False,
        use_ddim=False,
        use_lcm=True),
    data_preprocessor=dict(
        bgr_to_rgb=True,
        mean=[
            123.675,
            116.28,
            103.53,
        ],
        pad_size_divisor=32,
        std=[
            58.395,
            57.12,
            57.375,
        ],
        type='DetDataPreprocessor'),
    neck=dict(
        in_channels=[
            256,
            512,
            1024,
            2048,
        ],
        num_outs=4,
        out_channels=256,
        type='LAMFPN'),
    test_cfg=dict(
        min_bbox_size=0,
        nms=dict(iou_threshold=0.5, type='nms'),
        score_thr=0.5,
        use_nms=True),
    type='DiffusionDet')
optim_wrapper = dict(
    _scope_='mmdet',
    clip_grad=dict(max_norm=1.0, norm_type=2),
    optimizer=dict(lr=2.5e-05, type='AdamW', weight_decay=0.0001),
    type='OptimWrapper')
param_scheduler = [
    dict(begin=0, by_epoch=True, end=5, start_factor=0.01, type='LinearLR'),
    dict(
        begin=0,
        by_epoch=True,
        end=100,
        gamma=0.1,
        milestones=[
            70,
            90,
        ],
        type='MultiStepLR'),
]
test_cfg = dict(_scope_='mmdet', type='TestLoop')
test_dataloader = dict(
    batch_size=4,
    dataset=dict(
        _scope_='mmdet',
        ann_file='annotations/kfold/train_fold0.json',
        data_prefix=dict(img='test/'),
        data_root=
        '/media/ross/8TB/project/lsh/chromosome/dataset/seflmake/chromosome202250604_NoResizeNoAug/',
        metainfo=dict(
            classes=(
                'A1',
                'A2',
                'A3',
                'B4',
                'B5',
                'C10',
                'C11',
                'C12',
                'C6',
                'C7',
                'C8',
                'C9',
                'D13',
                'D14',
                'D15',
                'E16',
                'E17',
                'E18',
                'F19',
                'F20',
                'G21',
                'G22',
                'X',
                'Y',
            ),
            palette=[
                (
                    95,
                    32,
                    0,
                ),
                (
                    220,
                    20,
                    60,
                ),
                (
                    119,
                    11,
                    32,
                ),
                (
                    0,
                    60,
                    100,
                ),
                (
                    0,
                    80,
                    100,
                ),
                (
                    0,
                    0,
                    70,
                ),
                (
                    50,
                    100,
                    0,
                ),
                (
                    100,
                    170,
                    30,
                ),
                (
                    142,
                    0,
                    0,
                ),
                (
                    70,
                    70,
                    70,
                ),
                (
                    100,
                    40,
                    40,
                ),
                (
                    55,
                    90,
                    80,
                ),
                (
                    220,
                    20,
                    60,
                ),
                (
                    255,
                    0,
                    0,
                ),
                (
                    0,
                    0,
                    142,
                ),
                (
                    0,
                    0,
                    70,
                ),
                (
                    0,
                    60,
                    100,
                ),
                (
                    0,
                    80,
                    100,
                ),
                (
                    0,
                    0,
                    230,
                ),
                (
                    119,
                    11,
                    32,
                ),
                (
                    0,
                    0,
                    142,
                ),
                (
                    250,
                    170,
                    30,
                ),
                (
                    220,
                    220,
                    0,
                ),
                (
                    175,
                    116,
                    175,
                ),
            ]),
        pipeline=[
            dict(
                backend_args=None,
                imdecode_backend='pillow',
                type='LoadImageFromFile'),
            dict(
                backend='pillow',
                keep_ratio=True,
                scale=(
                    1333,
                    800,
                ),
                type='Resize'),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(
                meta_keys=(
                    'img_id',
                    'img_path',
                    'ori_shape',
                    'img_shape',
                    'scale_factor',
                ),
                type='PackDetInputs'),
        ],
        test_mode=True,
        type='CocoDataset'),
    drop_last=False,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(_scope_='mmdet', shuffle=False, type='DefaultSampler'))
test_evaluator = dict(
    _scope_='mmdet',
    ann_file=
    '/media/ross/8TB/project/lsh/chromosome/dataset/seflmake/chromosome202250604_NoResizeNoAug/annotations/kfold/train_fold0.json',
    backend_args=None,
    classwise=True,
    format_only=False,
    metric='bbox',
    type='DensityCocoMetric')
test_pipeline = [
    dict(
        backend_args=None, imdecode_backend='pillow',
        type='LoadImageFromFile'),
    dict(
        backend='pillow', keep_ratio=True, scale=(
            1333,
            800,
        ), type='Resize'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(
        meta_keys=(
            'img_id',
            'img_path',
            'ori_shape',
            'img_shape',
            'scale_factor',
        ),
        type='PackDetInputs'),
]
train_cfg = dict(max_epochs=100, type='EpochBasedTrainLoop', val_interval=1)
train_dataloader = dict(
    batch_sampler=dict(_scope_='mmdet', type='AspectRatioBatchSampler'),
    batch_size=8,
    dataset=dict(
        _scope_='mmdet',
        ann_file='annotations/kfold/train_fold0.json',
        data_prefix=dict(img='train_val/'),
        data_root=
        '/media/ross/8TB/project/lsh/chromosome/dataset/seflmake/chromosome202250604_NoResizeNoAug/',
        filter_cfg=dict(filter_empty_gt=True, min_size=1),
        metainfo=dict(
            classes=(
                'A1',
                'A2',
                'A3',
                'B4',
                'B5',
                'C10',
                'C11',
                'C12',
                'C6',
                'C7',
                'C8',
                'C9',
                'D13',
                'D14',
                'D15',
                'E16',
                'E17',
                'E18',
                'F19',
                'F20',
                'G21',
                'G22',
                'X',
                'Y',
            ),
            palette=[
                (
                    95,
                    32,
                    0,
                ),
                (
                    220,
                    20,
                    60,
                ),
                (
                    119,
                    11,
                    32,
                ),
                (
                    0,
                    60,
                    100,
                ),
                (
                    0,
                    80,
                    100,
                ),
                (
                    0,
                    0,
                    70,
                ),
                (
                    50,
                    100,
                    0,
                ),
                (
                    100,
                    170,
                    30,
                ),
                (
                    142,
                    0,
                    0,
                ),
                (
                    70,
                    70,
                    70,
                ),
                (
                    100,
                    40,
                    40,
                ),
                (
                    55,
                    90,
                    80,
                ),
                (
                    220,
                    20,
                    60,
                ),
                (
                    255,
                    0,
                    0,
                ),
                (
                    0,
                    0,
                    142,
                ),
                (
                    0,
                    0,
                    70,
                ),
                (
                    0,
                    60,
                    100,
                ),
                (
                    0,
                    80,
                    100,
                ),
                (
                    0,
                    0,
                    230,
                ),
                (
                    119,
                    11,
                    32,
                ),
                (
                    0,
                    0,
                    142,
                ),
                (
                    250,
                    170,
                    30,
                ),
                (
                    220,
                    220,
                    0,
                ),
                (
                    175,
                    116,
                    175,
                ),
            ]),
        pipeline=[
            dict(
                backend_args=None,
                imdecode_backend='pillow',
                type='LoadImageFromFile'),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(prob=0.5, type='RandomFlip'),
            dict(
                transforms=[
                    [
                        dict(
                            backend='pillow',
                            keep_ratio=True,
                            scales=[
                                (
                                    480,
                                    1333,
                                ),
                                (
                                    512,
                                    1333,
                                ),
                                (
                                    544,
                                    1333,
                                ),
                                (
                                    576,
                                    1333,
                                ),
                                (
                                    608,
                                    1333,
                                ),
                                (
                                    640,
                                    1333,
                                ),
                                (
                                    672,
                                    1333,
                                ),
                                (
                                    704,
                                    1333,
                                ),
                                (
                                    736,
                                    1333,
                                ),
                                (
                                    768,
                                    1333,
                                ),
                                (
                                    800,
                                    1333,
                                ),
                            ],
                            type='RandomChoiceResize'),
                    ],
                    [
                        dict(
                            backend='pillow',
                            keep_ratio=True,
                            scales=[
                                (
                                    400,
                                    1333,
                                ),
                                (
                                    500,
                                    1333,
                                ),
                                (
                                    600,
                                    1333,
                                ),
                            ],
                            type='RandomChoiceResize'),
                        dict(
                            allow_negative_crop=True,
                            crop_size=(
                                384,
                                600,
                            ),
                            crop_type='absolute_range',
                            type='RandomCrop'),
                        dict(
                            backend='pillow',
                            keep_ratio=True,
                            scales=[
                                (
                                    480,
                                    1333,
                                ),
                                (
                                    512,
                                    1333,
                                ),
                                (
                                    544,
                                    1333,
                                ),
                                (
                                    576,
                                    1333,
                                ),
                                (
                                    608,
                                    1333,
                                ),
                                (
                                    640,
                                    1333,
                                ),
                                (
                                    672,
                                    1333,
                                ),
                                (
                                    704,
                                    1333,
                                ),
                                (
                                    736,
                                    1333,
                                ),
                                (
                                    768,
                                    1333,
                                ),
                                (
                                    800,
                                    1333,
                                ),
                            ],
                            type='RandomChoiceResize'),
                    ],
                ],
                type='RandomChoice'),
            dict(type='PackDetInputs'),
        ],
        type='CocoDataset'),
    num_workers=2,
    persistent_workers=True,
    sampler=dict(shuffle=True, type='DefaultSampler'))
train_pipeline = [
    dict(
        backend_args=None, imdecode_backend='pillow',
        type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(method='gaussian', sigma=4.0, type='LoadDensityAnnotation'),
    dict(type='PackDetInputsWithDensity'),
    dict(prob=0.5, type='RandomFlip'),
    dict(
        transforms=[
            [
                dict(
                    backend='pillow',
                    keep_ratio=True,
                    scales=[
                        (
                            480,
                            1333,
                        ),
                        (
                            512,
                            1333,
                        ),
                        (
                            544,
                            1333,
                        ),
                        (
                            576,
                            1333,
                        ),
                        (
                            608,
                            1333,
                        ),
                        (
                            640,
                            1333,
                        ),
                        (
                            672,
                            1333,
                        ),
                        (
                            704,
                            1333,
                        ),
                        (
                            736,
                            1333,
                        ),
                        (
                            768,
                            1333,
                        ),
                        (
                            800,
                            1333,
                        ),
                    ],
                    type='RandomChoiceResize'),
            ],
            [
                dict(
                    backend='pillow',
                    keep_ratio=True,
                    scales=[
                        (
                            400,
                            1333,
                        ),
                        (
                            500,
                            1333,
                        ),
                        (
                            600,
                            1333,
                        ),
                    ],
                    type='RandomChoiceResize'),
                dict(
                    allow_negative_crop=True,
                    crop_size=(
                        384,
                        600,
                    ),
                    crop_type='absolute_range',
                    type='RandomCrop'),
                dict(
                    backend='pillow',
                    keep_ratio=True,
                    scales=[
                        (
                            480,
                            1333,
                        ),
                        (
                            512,
                            1333,
                        ),
                        (
                            544,
                            1333,
                        ),
                        (
                            576,
                            1333,
                        ),
                        (
                            608,
                            1333,
                        ),
                        (
                            640,
                            1333,
                        ),
                        (
                            672,
                            1333,
                        ),
                        (
                            704,
                            1333,
                        ),
                        (
                            736,
                            1333,
                        ),
                        (
                            768,
                            1333,
                        ),
                        (
                            800,
                            1333,
                        ),
                    ],
                    type='RandomChoiceResize'),
            ],
        ],
        type='RandomChoice'),
    dict(type='PackDetInputs'),
]
val_cfg = dict(_scope_='mmdet', type='ValLoop')
val_dataloader = dict(
    batch_size=8,
    dataset=dict(
        _scope_='mmdet',
        ann_file='annotations/kfold/train_fold0.json',
        data_prefix=dict(img='train_val/'),
        data_root=
        '/media/ross/8TB/project/lsh/chromosome/dataset/seflmake/chromosome202250604_NoResizeNoAug/',
        metainfo=dict(
            classes=(
                'A1',
                'A2',
                'A3',
                'B4',
                'B5',
                'C10',
                'C11',
                'C12',
                'C6',
                'C7',
                'C8',
                'C9',
                'D13',
                'D14',
                'D15',
                'E16',
                'E17',
                'E18',
                'F19',
                'F20',
                'G21',
                'G22',
                'X',
                'Y',
            ),
            palette=[
                (
                    95,
                    32,
                    0,
                ),
                (
                    220,
                    20,
                    60,
                ),
                (
                    119,
                    11,
                    32,
                ),
                (
                    0,
                    60,
                    100,
                ),
                (
                    0,
                    80,
                    100,
                ),
                (
                    0,
                    0,
                    70,
                ),
                (
                    50,
                    100,
                    0,
                ),
                (
                    100,
                    170,
                    30,
                ),
                (
                    142,
                    0,
                    0,
                ),
                (
                    70,
                    70,
                    70,
                ),
                (
                    100,
                    40,
                    40,
                ),
                (
                    55,
                    90,
                    80,
                ),
                (
                    220,
                    20,
                    60,
                ),
                (
                    255,
                    0,
                    0,
                ),
                (
                    0,
                    0,
                    142,
                ),
                (
                    0,
                    0,
                    70,
                ),
                (
                    0,
                    60,
                    100,
                ),
                (
                    0,
                    80,
                    100,
                ),
                (
                    0,
                    0,
                    230,
                ),
                (
                    119,
                    11,
                    32,
                ),
                (
                    0,
                    0,
                    142,
                ),
                (
                    250,
                    170,
                    30,
                ),
                (
                    220,
                    220,
                    0,
                ),
                (
                    175,
                    116,
                    175,
                ),
            ]),
        pipeline=[
            dict(
                backend_args=None,
                imdecode_backend='pillow',
                type='LoadImageFromFile'),
            dict(
                backend='pillow',
                keep_ratio=True,
                scale=(
                    1333,
                    800,
                ),
                type='Resize'),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(
                meta_keys=(
                    'img_id',
                    'img_path',
                    'ori_shape',
                    'img_shape',
                    'scale_factor',
                ),
                type='PackDetInputs'),
        ],
        test_mode=True,
        type='CocoDataset'),
    drop_last=False,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(_scope_='mmdet', shuffle=False, type='DefaultSampler'))
val_evaluator = dict(
    _scope_='mmdet',
    ann_file=
    '/media/ross/8TB/project/lsh/chromosome/dataset/seflmake/chromosome202250604_NoResizeNoAug/annotations/kfold/train_fold0.json',
    backend_args=None,
    format_only=False,
    metric='bbox',
    type='DensityCocoMetric')
vis_backends = [
    dict(_scope_='mmdet', type='LocalVisBackend'),
    dict(type='TensorboardVisBackend'),
]
visualizer = dict(
    _scope_='mmdet',
    name='visualizer',
    type='DetLocalVisualizer',
    vis_backends=[
        dict(type='LocalVisBackend'),
        dict(type='TensorboardVisBackend'),
    ])
work_dir = './work_dirs/diffusiondet_r50_fpn_chromoKD_1lcm_1lamfpn_0ddim_0distill'
